# Generated by Django 6.0 on 2026-01-02 12:42

import django.core.validators
import uploads.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_eye_image', models.ImageField(upload_to=uploads.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic'])], verbose_name='Left Eye Image')),
                ('right_eye_image', models.ImageField(upload_to=uploads.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic'])], verbose_name='Right Eye Image')),
                ('camera_specs_image', models.ImageField(upload_to=uploads.models.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'heic'])], verbose_name='Camera Specifications Screenshot')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Date')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
