# Generated by Django 6.0 on 2026-01-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='consent',
            field=models.BooleanField(default=False, verbose_name='I consent to the use of my eye images for AI model validation'),
        ),
    ]
