# Generated by Django 6.0 on 2026-01-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_submission_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='camera_type',
            field=models.CharField(choices=[('front', 'Front Camera'), ('back', 'Back Camera')], default='back', help_text='Which camera did you use to take the eye images?', max_length=10, verbose_name='Camera Type Used'),
        ),
    ]
